#include<stdio.h>
int main()
{

printf("The Biot-Savart law is an equation describing the magnetic field\ngenerated by electric current. It relates the magnatic field to the magnitude\n deriction,length and proximity of the electric field.\n  ");
return 0;
}
